// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTab(arg1:number):Promise<boolean>;

export function GetTabs():Promise<Array<main.Tab>>;

export function Greet(arg1:string):Promise<string>;

export function InsertTab(arg1:string):Promise<boolean>;

export function UpdateTab(arg1:main.Tab):Promise<boolean>;
