// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTab(arg1) {
  return window['go']['main']['App']['DeleteTab'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertTab(arg1) {
  return window['go']['main']['App']['InsertTab'](arg1);
}

export function UpdateTab(arg1) {
  return window['go']['main']['App']['UpdateTab'](arg1);
}
