// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteTab(arg1) {
  return window['go']['main']['App']['DeleteTab'](arg1);
}

export function GetNoteById(arg1) {
  return window['go']['main']['App']['GetNoteById'](arg1);
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertNote(arg1, arg2) {
  return window['go']['main']['App']['InsertNote'](arg1, arg2);
}

export function InsertTab(arg1) {
  return window['go']['main']['App']['InsertTab'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}

export function UpdateTab(arg1) {
  return window['go']['main']['App']['UpdateTab'](arg1);
}
