// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:number):Promise<boolean>;

export function DeleteTab(arg1:number):Promise<boolean>;

export function GetNoteById(arg1:number):Promise<main.Note>;

export function GetNotes(arg1:number):Promise<Array<main.Note>>;

export function GetTabs():Promise<Array<main.Tab>>;

export function Greet(arg1:string):Promise<string>;

export function InsertNote(arg1:string,arg2:number):Promise<number>;

export function InsertTab(arg1:string):Promise<boolean>;

export function UpdateNote(arg1:string,arg2:number):Promise<boolean>;

export function UpdateTab(arg1:main.Tab):Promise<boolean>;
