// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForZombieAssets(arg1, arg2) {
  return window['go']['main']['App']['CheckForZombieAssets'](arg1, arg2);
}

export function DecodeData(arg1) {
  return window['go']['main']['App']['DecodeData'](arg1);
}

export function DeleteNote(arg1, arg2) {
  return window['go']['main']['App']['DeleteNote'](arg1, arg2);
}

export function DeleteTab(arg1) {
  return window['go']['main']['App']['DeleteTab'](arg1);
}

export function DomReady() {
  return window['go']['main']['App']['DomReady']();
}

export function GetNoteById(arg1) {
  return window['go']['main']['App']['GetNoteById'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function ImageSize(arg1) {
  return window['go']['main']['App']['ImageSize'](arg1);
}

export function InsertNote(arg1, arg2) {
  return window['go']['main']['App']['InsertNote'](arg1, arg2);
}

export function InsertTab(arg1) {
  return window['go']['main']['App']['InsertTab'](arg1);
}

export function ReadNote(arg1, arg2) {
  return window['go']['main']['App']['ReadNote'](arg1, arg2);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3);
}

export function SearchNotes(arg1, arg2) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}

export function UpdateTab(arg1) {
  return window['go']['main']['App']['UpdateTab'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
