name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Nite'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'Nite'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'Nite'
            platform: 'darwin/universal'
            os: 'macos-latest'
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          wails-version: "v2.9.0"
          go-version: '1.24'